image: python:3.6

pipelines:
  default:
    - step:
        name: Build
        caches:
          - pip
        script:
          - pip install homeassistant
          - cp secrets.yaml.dist secrets.yaml
    - step:
        name: Check config
        script:
          - hass -c . --script check_config

