# Available icons. Replace "mdi-" with "mdi:"
# https://cdn.materialdesignicons.com/2.3.54/

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  customize: !include_dir_merge_named customize/
  packages: !include_dir_named components/packages

automation: !include_dir_merge_list automation
script: !include_dir_merge_named components/scripts

# Enables configuration UI
config:

lovelace:
  mode: yaml

# Enable the system-health card in dev-info
system_health:

