title: Automations
icon: mdi:timer
cards:
  - type: entities
    title: Automations for Lights
    show_header_toggle: false
    entities:
      - entity: automation.turn_on_lights_to_wake_us_up
      - entity: automation.turn_off_lights_before_work
      - entity: automation.turn_on_lights_before_sunset
      - entity: automation.turn_off_lights_midnight
      - entity: automation.turn_on_outside_lights_early_morning
      - entity: automation.turn_off_outside_lights_sunrise
      - entity: automation.turn_on_outside_lights_sunset
      - entity: automation.turn_off_outside_lights_1_00am
  - type: entities
    title: Sensors
    show_header_toggle: false
    entities:
      - entity: automation.announce_kitchen_door_opened
      - entity: automation.announce_kitchen_door_closed

