# https://www.home-assistant.io/integrations/binary_sensor

binary_sensor:
  - platform: template
    sensors:
      halloween_month:
        friendly_name: "Month of Halloween"
        value_template: "{{ now().month == 10 }}"

      thanksgiving_month:
        friendly_name: "Month of Thanksgiving"
        value_template: "{{ now().month == 11 }}"

      christmas_month:
        friendly_name: "Month of Christmas"
        value_template: "{{ now().month == 12 }}"

      today_is_someones_birthday:
        friendly_name: "Today is Someone's Birthday"
        value_template: !secret birthday_evaluator

  # Service will return a single object with key "busy" and a boolean value.
  # Sensor value to match the boolean value.
  # Example payload: {"busy":false}
  - platform: rest
    resource: !secret teams_rest_url
    name: "Teams on call"
    value_template: "{{ value_json.busy }}"

