# https://www.home-assistant.io/integrations/binary_sensor

binary_sensor:
  - platform: template
    sensors:
      guest_bathroom_occupancy:
        friendly_name: 'Guest Bathroom Occupancy'
        device_class: motion
        value_template: "{{ is_state('sensor.zooz_zse40_4_in_1_sensor_burglar', '0') == False }}"

