---
# Order matters

automation.turn_on_lights_to_wake_us_up:
  friendly_name: Bedroom Lights On at 6:30am
  icon: mdi:lightbulb-outline

automation.turn_off_lights_before_work:
  friendly_name: Bedroom Lights Off Before Work
  icon: mdi:lightbulb-outline

automation.turn_on_lights_before_sunset:
  friendly_name: Bedroom Lights On Before Sunset
  icon: mdi:lightbulb-outline

automation.turn_off_lee_s_bedside_by_8_30pm:
  friendly_name: Turn Off Lee's Bedside By 8:30pm
  icon: mdi:lightbulb-outline

automation.turn_off_andrei_s_bedside_by_9_00pm:
  friendly_name: Turn Off Andrei's Bedside Off By 9:00pm
  icon: mdi:lightbulb-outline

automation.turn_on_outside_lights_early_morning:
  friendly_name: Deck Lights On at 6:15am
  icon: mdi:lightbulb-outline

automation.turn_off_outside_lights_sunrise:
  friendly_name: Deck Lights Off at Sunrise
  icon: mdi:lightbulb-outline

automation.turn_on_outside_lights_sunset:
  friendly_name: Deck Lights On at Sunset
  icon: mdi:lightbulb-outline

automation.turn_on_night_light_at_sunset:
  friendly_name: Turn On Night-Light at Sunset
  icon: mdi:led-strip

automation.turn_off_night_light_after_sunrise:
  friendly_name: Turn Off Night-Light After Sunrise
  icon: mdi:led-strip

automation.turn_on_dining_room_lamp_before_sunset:
  friengly_name: Turn On Dining Room Lamp Before Sunset
  icon: mdi:lamp

automation.turn_off_dining_room_lamp:
  friengly_name: Turn On Dining Room Lamp 10:30pm
  icon: mdi:lamp

automation.announce_door_opened:
  friendly_name: Announce Door Opened
  icon: mdi:door-open

automation.announce_door_opened_event:
  friendly_name: Announce Door Opened (Event)
  icon: mdi:door-open

automation.announce_door_closed:
  friendly_name: Announce Door Closed
  icon: mdi:door-closed

automation.announce_door_closed_event:
  friendly_name: Announce Door Closed (Event)
  icon: mdi:door-closed

automation.motion_send_camera_snapshot_notification_on_motion:
  friendly_name: Send Camera Snapshot Notification on Motion
  device_class: motion

