# Order matters

automation.turn_on_lights_to_wake_us_up:
  friendly_name: Bedroom Lights On at 6:10am
  icon: mdi:lightbulb-outline

automation.turn_off_lights_before_work:
  friendly_name: Bedroom Lights Off at 7:45am
  icon: mdi:lightbulb-outline

automation.turn_on_lights_before_sunset:
  friendly_name: Bedroom Lights On Before Sunset
  icon: mdi:lightbulb-outline

automation.turn_off_lights_9_30pm:
  friendly_name: Bedroom Lights Off at 9:30pm
  icon: mdi:lightbulb-outline

automation.turn_on_outside_lights_early_morning:
  friendly_name: Deck Lights On at 6:15am
  icon: mdi:lightbulb-outline

automation.turn_off_outside_lights_sunrise:
  friendly_name: Deck Lights Off at Sunrise
  icon: mdi:lightbulb-outline

automation.turn_on_outside_lights_sunset:
  friendly_name: Deck Lights On at Sunset
  icon: mdi:lightbulb-outline

automation.turn_off_outside_lights_11_15pm:
  friendly_name: Deck Lights Off at 11:15pm
  icon: mdi:lightbulb-outline

automation.turn_on_night_light_at_sunset:
  friendly_name: Turn On Night-Light at Sunset
  icon: mdi:led-strip

automation.turn_off_night_light_8_00am:
  friendly_name: Turn Off Night-Light 8:00am
  icon: mdi:led-strip

automation.turn_on_dining_room_lamp_before_sunset:
  friengly_name: Turn On Dining Room Lamp Before Sunset
  icon: mdi:lamp

automation.turn_off_dining_room_lamp:
  friengly_name: Turn On Dining Room Lamp 10:30pm
  icon: mdi:lamp

automation.announce_kitchen_door_opened:
  friendly_name: Announce Kitchen Door Opened
  icon: mdi:door-open

automation.announce_kitchen_door_closed:
  friendly_name: Announce Kitchen Door Closed
  icon: mdi:door-closed

automation.announce_front_door_opened:
  friendly_name: Announce Front Door Opened
  icon: mdi:door-open

automation.announce_front_door_closed:
  friendly_name: Announce Front Door Closed
  icon: mdi:door-closed

automation.turn_off_air_purifier_morning:
  friendly_name: Turn Off Air Purifier Morning
  icon: mdi:air-filter

automation.turn_on_air_purifier_mid_morning:
  friendly_name: Turn On Air Purifier Mid-Morning
  icon: mdi:air-filter

