automation.turn_on_lights_to_wake_us_up:
  friendly_name: Turn on Lights to Wake Us Up
  icon: mdi:lightbulb-outline

automation.turn_off_lights_before_work:
  friendly_name: Turn Off Lights After Waking Us Up
  icon: mdi:lightbulb-outline

automation.turn_on_lights_sunset:
  friendly_name: Turn On Lights - Sunset
  icon: mdi:lightbulb-outline

automation.turn_off_lights_midnight:
  friendly_name: Turn Off Lights - Midnight
  icon: mdi:lightbulb-outline

automation.turn_on_outside_lights_early_morning:
  friendly_name: Turn On Outside Lights - Early Morning
  icon: mdi:lightbulb-outline

automation.turn_off_outside_lights_sunrise:
  friendly_name: Turn Off Outside Lights - Sunrise
  icon: mdi:lightbulb-outline

automation.turn_on_outside_lights_sunset:
  friendly_name: Turn On Outside Lights - Sunset
  icon: mdi:lightbulb-outline

automation.turn_off_outside_lights_100am:
  friendly_name: Turn Off Outside Lights - 1:00am
  icon: mdi:lightbulb-outline

automation.spike_basking_lights_on_in_morning:
  friendly_name: Spike Basking Lights On In Morning
  icon: mdi:lightbulb-outline

automation.spike_night_light_on_at_night:
  friendly_name: Spike Night Light On At Night
  icon: mdi:lightbulb-outline

