automation.turn_on_lights_to_wake_us_up:
  friendly_name: Turn on Lights to Wake Us Up
  icon: mdi:lightbulb-outline

automation.turn_off_lights_before_work:
  friendly_name: Turn Off Lights After Waking Us Up
  icon: mdi:lightbulb-outline

automation.turn_on_lights_sunset:
  friendly_name: Turn On Lights - Sunset
  icon: mdi:lightbulb-outline

automation.turn_off_lights_midnight:
  friendly_name: Turn Off Lights - Midnight
  icon: mdi:lightbulb-outline

automation.turn_on_lights_eob:
  friendly_name: Turn on Lights EOB
  icon: mdi:lightbulb-outline

automation.turn_off_lights_end_of_night:
  friendly_name: Turn Off Lights - End of Night
  icon: mdi:lightbulb-outline
