# Order matters

automation.turn_on_lights_to_wake_us_up:
  friendly_name: Bedroom Lights On at 6:40am
  icon: mdi:lightbulb-outline

automation.turn_off_lights_before_work:
  friendly_name: Bedroom Lights Off at 7:45am
  icon: mdi:lightbulb-outline

automation.turn_on_lights_before_sunset:
  friendly_name: Bedroom Lights On Before Sunset
  icon: mdi:lightbulb-outline

automation.turn_off_lights_midnight:
  friendly_name: Bedroom Lights Off at 9:30pm
  icon: mdi:lightbulb-outline

automation.turn_on_outside_lights_early_morning:
  friendly_name: Deck Lights On at 6:15am
  icon: mdi:lightbulb-outline

automation.turn_off_outside_lights_sunrise:
  friendly_name: Deck Lights Off at Sunrise
  icon: mdi:lightbulb-outline

automation.turn_on_outside_lights_sunset:
  friendly_name: Deck Lights On at Sunset
  icon: mdi:lightbulb-outline

automation.turn_off_outside_lights_11_15pm:
  friendly_name: Deck Lights Off at 11:15pm
  icon: mdi:lightbulb-outline

automation.announce_kitchen_door_opened:
  friendly_name: Announce Kitchen Door Opened
  icon: mdi:door-open

automation.announce_kitchen_door_closed:
  friendly_name: Announce Kitchen Door Closed
  icon: mdi:door-closed

