# Fade lights on in the morning to simulate a sunrise next to my face.
- alias: Turn on Lights to Wake Us Up
  initial_state: True
  trigger:
    platform: time
    at: "06:40:00"
  condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: light.turn_on
    data:
      entity_id: light.hue_white_lamp_1
      brightness: 255
      transition: 1800

- alias: Turn Off Lights Before Work
  initial_state: True
  trigger:
    platform: time
    at: "07:45:00"
  condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: light.turn_off
    entity_id: light.hue_white_lamp_1

# Gradually fade in lights as the sun sets into the night.
- alias: Turn On Lights Before Sunset
  initial_state: True
  trigger:
    platform: sun
    event: sunset
    offset: "-1:15:00"
  action:
    service: light.turn_on
    data:
      entity_id:
        - light.hue_white_lamp_1
        - light.hue_white_lamp_2
      brightness: 255
      transition: 1500

- alias: Turn Off Lights 9:30pm
  initial_state: True
  trigger:
    platform: time
    at: "21:30:00"
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.hue_white_lamp_1
        - light.hue_white_lamp_2

- alias: Turn On Night-Light at Sunset
  initial_state: True
  trigger:
    platform: sun
    event: sunset
    offset: "-0:30:00"
  action:
    service: light.turn_on
    data:
      entity_id: light.night_light
      brightness: 1

- alias: Turn Off Night-Light 8:00am
  initial_state: True
  trigger:
    platform: time
    at: "08:00:00"
  action:
    service: light.turn_off
    data:
      entity_id: light.night_light

