- alias: Turn on Lights to Wake Us Up
  initial_state: True
  trigger:
    platform: time
    at: "06:10:00"
  condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: script.wakeup

- alias: Turn Off Lights Before Work
  initial_state: True
  trigger:
    platform: time
    at: "07:45:00"
  condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: light.turn_off
    entity_id: light.hue_white_lamp_1

- alias: Turn On Lights Sunset
  initial_state: True
  trigger:
    platform: time
    at: "18:10:00"
  action:
    service: light.turn_on
    data:
      entity_id:
        - light.hue_white_lamp_1
        - light.hue_white_lamp_2

- alias: Turn Off Lights Midnight
  initial_state: True
  trigger:
    platform: time
    at: "21:45:00"
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.hue_white_lamp_1
        - light.hue_white_lamp_2

