- alias: Turn On Christmas Lights at Sunset
  trigger:
    platform: sun
    event: sunset
  action:
    service: switch.turn_on
    data:
      entity_id:
        - switch.wemo_mini_3
        - switch.tp_link_smart_plug_ac7b
        - switch.tp_link_smart_plug_ad70
        - switch.tp_link_smart_plug_d6d2
        - switch.tp_link_smart_plug_ac23

- alias: Turn Off Christmas Lights 11:13pm
  trigger:
    platform: time
    at: "23:13:00"
  action:
    service: switch.turn_off
    data:
      entity_id:
        - switch.wemo_mini_3
        - switch.tp_link_smart_plug_ac7b
        - switch.tp_link_smart_plug_ad70
        - switch.tp_link_smart_plug_d6d2
        - switch.tp_link_smart_plug_ac23

