- alias: Announce Door Opened
  id: "announce_door_opened"
  trigger:
    - platform: state
      entity_id: binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open_2
      to: "on"
      variables:
        location_name: "Kitchen"
    - platform: state
      entity_id: binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open
      to: "on"
      variables:
        location_name: "Front"
    - platform: state
      entity_id: binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open_4
      to: "on"
      variables:
        location_name: "Laundry"
    - platform: state
      entity_id: binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open_3
      to: "on"
      variables:
        location_name: "Office"
  mode: queued
  condition:
    - condition: state
      entity_id: binary_sensor.halloween_month
      state: "off"
    - condition: state
      entity_id: binary_sensor.thanksgiving_month
      state: "off"
    - condition: state
      entity_id: binary_sensor.christmas_month
      state: "off"
  action:
    service: script.sonos_say
    data:
      message: "{{ location_name }} door open"
      delay: "00:00:03"

- alias: Announce Door Closed
  id: "announce_door_closed"
  trigger:
    - platform: state
      entity_id: binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open_2
      to: "off"
      variables:
        location_name: "Kitchen"
    - platform: state
      entity_id: binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open
      to: "off"
      variables:
        location_name: "Front"
    - platform: state
      entity_id: binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open_4
      to: "off"
      variables:
        location_name: "Laundry"
    - platform: state
      entity_id: binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open_3
      to: "off"
      variables:
        location_name: "Office"
  mode: queued
  condition:
    - condition: state
      entity_id: binary_sensor.halloween_month
      state: "off"
    - condition: state
      entity_id: binary_sensor.thanksgiving_month
      state: "off"
    - condition: state
      entity_id: binary_sensor.christmas_month
      state: "off"
  action:
    service: script.sonos_say
    data:
      message: "{{ location_name }} door closed"
      delay: "00:00:03"

- alias: Announce Door Opened (Event)
  id: "announce_door_opened_event"
  trigger:
    platform: state
    entity_id:
      - binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open
      - binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open_2
      - binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open_3
      - binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open_4
    to: "on"
  mode: queued
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.halloween_month
              state: "on"
          sequence:
            - service: script.sonos_play_file
              data:
                audio_url: "audio/ghost01.mp3"
                delay: "00:00:08"
        - conditions:
            - condition: state
              entity_id: binary_sensor.thanksgiving_month
              state: "on"
          sequence:
            - service: script.sonos_play_file
              data:
                audio_url: "audio/turkey01.mp3"
                delay: "00:00:08"
        - conditions:
            - condition: state
              entity_id: binary_sensor.christmas_month
              state: "on"
          sequence:
            - service: script.sonos_play_file
              data:
                audio_url: "audio/christmas01.mp3"
                delay: "00:00:08"

- alias: Announce Door Closed (Event)
  id: "announce_door_closed_event"
  trigger:
    platform: state
    entity_id:
      - binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open
      - binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open_2
      - binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open_3
      - binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open_4
    to: "off"
  mode: queued
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.halloween_month
              state: "on"
          sequence:
            - service: script.sonos_play_file
              data:
                audio_url: "audio/howl01.mp3"
                delay: "00:00:08"
        - conditions:
            - condition: state
              entity_id: binary_sensor.thanksgiving_month
              state: "on"
          sequence:
            - service: script.sonos_play_file
              data:
                audio_url: "audio/turkey01.mp3"
                delay: "00:00:08"
        - conditions:
            - condition: state
              entity_id: binary_sensor.christmas_month
              state: "on"
          sequence:
            - service: script.sonos_play_file
              data:
                audio_url: "audio/christmas01.mp3"
                delay: "00:00:08"

