- alias: Announce Kitchen Door Opened
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_door_window_sensor_sensor
    from: 'off'
    to: 'on'
  mode: queued
  condition:
    condition: template
    value_template: >
      {% set month = now().month %}
      {{ month < 10 }}
  action:
    service: script.sonos_say
    data:
      message: 'Kitchen door open'
      delay: '00:00:05'

- alias: Announce Kitchen Door Opened (Halloween)
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_door_window_sensor_sensor
    from: 'off'
    to: 'on'
  mode: queued
  condition:
    condition: template
    value_template: >
      {% set month = now().month %}
      {{ month == 10 }}
  action:
    service: script.sonos_play_file
    data:
      audio_url: "audio/ghost01.mp3"
      delay: '00:00:08'

- alias: Announce Kitchen Door Opened (Thanksgiving)
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_door_window_sensor_sensor
    from: 'off'
    to: 'on'
  mode: queued
  condition:
    condition: template
    value_template: >
      {% set month = now().month %}
      {{ month == 11 }}
  action:
    service: script.sonos_play_file
    data:
      audio_url: "audio/turkey01.mp3"
      delay: '00:00:08'

- alias: Announce Kitchen Door Opened (Christmas)
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_door_window_sensor_sensor
    from: 'off'
    to: 'on'
  mode: queued
  condition:
    condition: template
    value_template: >
      {% set month = now().month %}
      {{ month == 12 }}
  action:
    service: script.sonos_play_file
    data:
      audio_url: "audio/christmas01.mp3"
      delay: '00:00:06'

- alias: Announce Kitchen Door Closed
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_door_window_sensor_sensor
    from: 'on'
    to: 'off'
  mode: queued
  condition:
    condition: template
    value_template: >
      {% set month = now().month %}
      {{ month < 10 }}
  action:
    service: script.sonos_say
    data:
      message: 'Kitchen door closed'
      delay: '00:00:05'

- alias: Announce Kitchen Door Closed (Halloween)
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_door_window_sensor_sensor
    from: 'on'
    to: 'off'
  mode: queued
  condition:
    condition: template
    value_template: >
      {% set month = now().month %}
      {{ month == 10 }}
  action:
    service: script.sonos_play_file
    data:
      audio_url: "audio/howl01.mp3"
      delay: '00:00:08'

- alias: Announce Kitchen Door Closed (Thanksgiving)
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_door_window_sensor_sensor
    from: 'on'
    to: 'off'
  mode: queued
  condition:
    condition: template
    value_template: >
      {% set month = now().month %}
      {{ month == 11 }}
  action:
    service: script.sonos_play_file
    data:
      audio_url: "audio/turkey01.mp3"
      delay: '00:00:08'

- alias: Announce Kitchen Door Closed (Christmas)
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_door_window_sensor_sensor
    from: 'on'
    to: 'off'
  mode: queued
  condition:
    condition: template
    value_template: >
      {% set month = now().month %}
      {{ month == 12 }}
  action:
    service: script.sonos_play_file
    data:
      audio_url: "audio/christmas01.mp3"
      delay: '00:00:06'

