---

- alias: Turn Off Air Purifier Weekdays (6:30am)
  id: turn_off_air_purifier_weekdays
  trigger:
    platform: time
    at: "06:30:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    action: switch.turn_off
    data:
      entity_id: switch.wemo_mini_1

- alias: Turn Off Air Purifier Weekends (7:15am)
  id: turn_off_air_purifier_weekends
  trigger:
    platform: time
    at: "07:15:00"
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    action: switch.turn_off
    data:
      entity_id: switch.wemo_mini_1

- alias: Turn On Air Purifier Mid-Morning
  id: turn_on_air_purifier_midmorning
  trigger:
    platform: time
    at: "07:20:00"
  action:
    action: switch.turn_on
    data:
      entity_id: switch.wemo_mini_1

- alias: Motion - Turn Off Guest Bathroom Fan When No Motion Detected
  id: motion_turn_off_guest_bathroom_fan_when_no_motion_detected
  trigger:
    - platform: state
      entity_id: binary_sensor.4_in_1_sensor_home_security_motion_detection
      from: 'on'
      to: 'off'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: switch.dimmer_dry_contact_relay
      state: 'on'
  action:
    - action: switch.turn_off
      entity_id: switch.dimmer_dry_contact_relay

- alias: Turn Off Primary Bathroom Fan After Period Of Time
  id: turn_off_primary_bathroom_fan_after_period_of_time
  description: >
    Turn off the fan if it's been on for 20 minutes. There isn't motion
    detection available.
  trigger:
    - platform: state
      entity_id: switch.dimmer_dry_contact_relay_2
      to: "on"
      for:
        minutes: 20
  condition: []
  action:
    - action: switch.turn_off
      entity_id: switch.dimmer_dry_contact_relay_2

