---

- alias: Turn Off Air Purifier Weekdays (6:45am)
  id: turn_off_air_purifier_weekdays
  trigger:
    platform: time
    at: "06:45:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: switch.turn_off
    data:
      entity_id: switch.wemo_mini_1

- alias: Turn Off Air Purifier Weekends (7:15am)
  id: turn_off_air_purifier_weekends
  trigger:
    platform: time
    at: "07:15:00"
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    service: switch.turn_off
    data:
      entity_id: switch.wemo_mini_1

- alias: Turn On Air Purifier Mid-Morning
  id: turn_on_air_purifier_midmorning
  trigger:
    platform: time
    at: "09:00:00"
  action:
    service: switch.turn_on
    data:
      entity_id: switch.wemo_mini_1

# Not considering motion, it's assumed if the shower is running.
- alias: Turn On Guest Bathroom Fan When Someone's Showering
  id: turn_on_guest_bathroom_fan_when_someones_showering
  trigger:
    - platform: state
      entity_id: binary_sensor.someone_is_showering_in_guest_bathroom
      to: "on"
      for: "00:01:00"
  condition:
    - condition: state
      entity_id: switch.dimmer_dry_contact_relay
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.dimmer_dry_contact_relay

- alias: Turn Off Guest Bathroom Fan When No Motion Detected
  id: turn_off_guest_bathroom_fan_when_no_motion_detected
  trigger:
    - platform: state
      entity_id: binary_sensor.4_in_1_sensor_home_security_motion_detection
      from: "on"
      to: "off"
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: switch.dimmer_dry_contact_relay
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.dimmer_dry_contact_relay

