- alias: Turn on Lights EOB
  initial_state: True
  trigger:
    platform: time
    at: "16:00:00"
  action:
    service: light.turn_on
    entity_id:
      - light.hue_white_lamp_1
      - light.hue_white_lamp_2

- alias: Turn Off Lights End of Night
  initial_state: True
  trigger:
    platform: time
    at: "22:10:00"
  action:
    service: light.turn_off
    entity_id:
      - light.hue_white_lamp_1
      - light.hue_white_lamp_2

