---
- alias: Motion - Turn On Guest Bathroom When Motion Detected Daytime
  id: motion_turn_on_guest_bathroom_when_motion_detected_daytime
  trigger:
    - platform: state
      entity_id: binary_sensor.4_in_1_sensor_home_security_motion_detection
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: light.zooz_unknown_type_a000_id_a008_level
      state: "off"
    - condition: time
      after: "06:00:00"
      before: "22:00:00"
  action:
    - service: light.turn_on
      entity_id: light.zooz_unknown_type_a000_id_a008_level
      data:
        brightness_pct: 100

- alias: Motion - Turn On Guest Bathroom When Motion Detected Night
  id: motion_turn_on_guest_bathroom_when_motion_detected_night
  trigger:
    - platform: state
      entity_id: binary_sensor.4_in_1_sensor_home_security_motion_detection
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: light.zooz_unknown_type_a000_id_a008_level
      state: "off"
    - condition: time
      after: "22:00:00"
      before: "06:00:00"
  action:
    - service: light.turn_on
      entity_id: light.zooz_unknown_type_a000_id_a008_level
      data:
        brightness_pct: 21

- alias: Motion - Turn Off Guest Bathroom When No Motion Detected
  id: motion_turn_off_guest_bathroom_when_no_motion_detected
  trigger:
    - platform: state
      entity_id: binary_sensor.4_in_1_sensor_home_security_motion_detection
      from: "on"
      to: "off"
      for:
        minutes: 3
  condition:
    - condition: state
      entity_id: light.zooz_unknown_type_a000_id_a008_level
      state: "on"
  action:
    - service: light.turn_off
      entity_id: light.zooz_unknown_type_a000_id_a008_level

# The automatic snapshot for Android works well so long as the receiving app
# is on the same network as Home Assistant, otherwise the notification won't
# have a camera snapshot.
- alias: Motion - Send Camera Snapshot Notification On Motion
  id: motion_send_camera_snapshot_notification_on_motion
  trigger:
    - platform: state
      entity_id: binary_sensor.office_motion_alarm
      to: "on"
      variables:
        camera_name: camera.office_main
    - platform: state
      entity_id: binary_sensor.laundry_motion_alarm
      to: "on"
      variables:
        camera_name: camera.laundry_main
  variables:
    snapshot_filename: >
      "{{ camera_name }}-{{ now().strftime('%Y%m%d-%H%M%S.%f') }}.jpg"
    snapshot_absolute_path: www/images/snapshots/{{ snapshot_filename }}
    # Secret made available as a variable in order to be able to concatenate
    # it with the filename.
    snapshot_base_url: !secret camera_snapshots_public_url
  action:
    - delay:
        seconds: 4
    - service: camera.snapshot
      data:
        entity_id: "{{ camera_name }}"
        filename: "{{ snapshot_absolute_path }}"
    - service: notify.mobile_apps_admin
      data:
        title: Camera Motion Detected
        message: "{{ trigger.to_state.name }}"
        data:
          image: "{{ snapshot_base_url }}/{{ snapshot_filename }}"
          # Use this instead for debugging, is only accessible on intranet.
          # image: "/api/camera_proxy/{{ camera_name }}"

