# Turn on the lights at 06:45 on weekdays unless the sun has already risen
# by 06:30. Summer months, when the sun rises very early, the lights won't
# come on. Winter months, when it rises closer to 07:30, the lights will.
- alias: Turn On Outside Lights Early Morning
  trigger:
    platform: time
    at: '06:45:00'
  condition:
    condition: and
    conditions:
      - condition: sun
        before: sunrise
        before_offset: '00:15:00'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    - service: light.turn_on
      data:
        entity_id: light.hue_color_lamp_1
        brightness: 255
        rgb_color: [255, 255, 255]

- alias: Turn Off Outside Lights Sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.hue_color_lamp_1

- alias: Turn On Outside Lights Sunset
  trigger:
    platform: sun
    event: sunset
    offset: '-00:15:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hue_color_lamp_1
        brightness_pct: 75
        rgb_color: [255, 255, 255]

- alias: Turn Off Outside Lights 1:00am
  trigger:
    platform: time
    at: "01:00:00"
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.hue_color_lamp_1

