- alias: Turn On Outside Lights Early Morning
  trigger:
    platform: time
    at: "06:15:00"
  action:
    - service: light.turn_on
      data:
        entity_id: light.hue_color_lamp_1
        brightness: 255
        rgb_color: [255, 255, 255]

- alias: Turn Off Outside Lights Sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.hue_color_lamp_1

- alias: Turn On Outside Lights Sunset
  trigger:
    platform: sun
    event: sunset
    offset: '-00:15:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hue_color_lamp_1
        brightness_pct: 75
        rgb_color: [255, 255, 255]

- alias: Turn Off Outside Lights 1:00am
  trigger:
    platform: time
    at: "01:00:00"
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.hue_color_lamp_1

