---
- alias: Laundry flooding
  id: 'laundry_flooding'
  trigger:
    platform: state
    entity_id: binary_sensor.flood_sensor_water_leak_state
    from: 'off'
    to: 'on'
    for:
      seconds: 15
  action:
    - service: notify.email
      data_template:
        title: "Laundry room is flooding"
        message: "You should probably check it out."
    - service: script.sonos_say
      data:
        # yamllint disable-line rule:line-length
        message: "Crikey! We've sprunga leak in the laundry room! I said crikey! We've sprunga leak in the laundry room!"
        delay: '00:00:15'
    - service: notify.mobile_apps
      data:
        message: "The laundry room is flooding"

- alias: Motion - Turn Off Guest Bathroom Fan When No Motion Detected
  id: 'motion_turn_off_guest_bathroom_fan_when_no_motion_detected'
  trigger:
    - platform: state
      entity_id: binary_sensor.4_in_1_sensor_home_security_motion_detection
      from: 'on'
      to: 'off'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: switch.dimmer_dry_contact_relay
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.dimmer_dry_contact_relay

- alias: Notification - Low Battery Notification
  id: 'notification_low_battery_notification'
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.z_wave_door_window_sensor_battery_level
        - sensor.z_wave_door_window_sensor_battery_level_2
        - sensor.z_wave_door_window_sensor_battery_level_4
        - sensor.z_wave_door_window_sensor_battery_level_3
        - sensor.flood_sensor_battery_level
        - sensor.4_in_1_sensor_battery_level
        - sensor.zcombo_g_smoke_co_alarm_battery_level
        - sensor.zcombo_g_smoke_co_alarm_battery_level_2
        - sensor.zcombo_g_smoke_co_alarm_battery_level_3
      below: 30
      for:
        hours: 1
        minutes: 0
        seconds: 0
  action:
    - service: notify.mobile_apps
      data:
        message: "{{ trigger.to_state.attributes.friendly_name }} Low"
        data:
          tag: bettery
          group: battery

