- alias: Notify of Water Under Kitchen Sink
  trigger:
    platform: state
    entity_id: binary_sensor.fibaro_system_fgfs101_flood_sensor_flood
    from: 'off'
    to: 'on'
    for:
      seconds: 15
  action:
    - service: notify.email
      data_template:
        title: "Water detected under kitchen sink"
        message: "You should probably check it out."
    - service: script.sonos_say
      data:
        message: "Crikey! We've sprunga leak under the sink! I said crikey! We've sprunga leak under the sink!"
        delay: '00:00:10'
    - service: notify.mobile_apps
      data:
        message: "There's water under the kitchen sink!"

- alias: Motion - Turn Off Guest Bathroom Fan When No Motion Detected
  id: 'motion_turn_off_guest_bathroom_fan_when_no_motion_detected'
  trigger:
    - platform: state
      entity_id: binary_sensor.guest_bathroom_occupancy
      from: 'on'
      to: 'off'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: switch.zooz_unknown_type_a000_id_a008_switch
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.zooz_unknown_type_a000_id_a008_switch

