---
- alias: Laundry flooding
  id: 'laundry_flooding'
  trigger:
    platform: state
    entity_id: binary_sensor.flood_sensor_water_leak_state
    from: 'off'
    to: 'on'
    for:
      seconds: 15
  action:
    - service: notify.email
      data_template:
        title: "Laundry room is flooding"
        message: "You should probably check it out."
    - service: script.sonos_say
      data:
        # yamllint disable-line rule:line-length
        message: "Crikey! We've sprunga leak in the laundry room! I said crikey! We've sprunga leak in the laundry room!"
        delay: '00:00:15'
    - service: notify.mobile_apps
      data:
        message: "The laundry room is flooding"

- alias: Motion - Turn Off Guest Bathroom Fan When No Motion Detected
  id: 'motion_turn_off_guest_bathroom_fan_when_no_motion_detected'
  trigger:
    - platform: state
      entity_id: binary_sensor.4_in_1_sensor_home_security_motion_detection
      from: 'on'
      to: 'off'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: switch.dimmer_dry_contact_relay
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.dimmer_dry_contact_relay

- alias: Low Battery Notification
  id: low_battery_notification
  description: Notify of low battery level in devices which have batteries
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.4_in_1_sensor_low_battery_level
        - binary_sensor.flood_sensor_low_battery_level
        - binary_sensor.z_wave_door_window_sensor_low_battery_level
        - binary_sensor.z_wave_door_window_sensor_low_battery_level_2
        - binary_sensor.z_wave_door_window_sensor_low_battery_level_3
        - binary_sensor.z_wave_door_window_sensor_low_battery_level_4
        - binary_sensor.zcombo_g_smoke_co_alarm_low_battery_level
        - binary_sensor.zcombo_g_smoke_co_alarm_low_battery_level_2
        - binary_sensor.zcombo_g_smoke_co_alarm_low_battery_level_3
      from: 'off'
      to: 'on'
      for:
        hours: 1
        minutes: 0
        seconds: 0
  action:
    - service: notify.mobile_apps
      data:
        message: The {{ trigger.to_state.attributes.friendly_name }} is Low
        data:
          tag: bettery
          group: battery
    - service: notify.email
      data_template:
        title: Low Battery Detected
        message: >-
          The {{ trigger.to_state.attributes.friendly_name }} is low.
          You should probably check it out.
 
