---

- alias: System - Clean Up Camera Snapshots Directory Periodically
  id: system_clean_up_camera_snapshots_directory_periodically
  description: >
    Daily delete of all camera shapshots files older than 4 days.
  trigger:
    - platform: time
      at: "05:27:18"
  action:
    - service: shell_command.clean_camera_snapshots
      data:
        days_threshold: 4

