name: Continuous integration

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  home_assistant:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Prep stub files in configuration folder
        run: |
          cp secrets.yaml.dist secrets.yaml
          touch home-assistant_v2.db
          touch home-assistant.log
          touch OZW_Log.txt

      - name: Home Assistant version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --version

      - name: Home Assistant check config
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --config . --script check_config --info all

