name: Continuous integration

on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  home_assistant:
    name: Home Assistant
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true

      - name: YAML lint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1

      - name: Home Assistant Core check configuration
        uses: frenck/action-home-assistant@941d5d917f4c1c7a7e7d4087526daf90d53f4437 # v1.4.1
        with:
          version: stable
          secrets: secrets.yaml.dist
          path: "."

