name: Continuous integration

on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  home_assistant:
    name: Home Assistant
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: YAML lint
        uses: ibiqlik/action-yamllint@v3

      - name: Home Assistant Core check configuration
        uses: frenck/action-home-assistant@v1.4
        with:
          version: stable
          secrets: secrets.yaml.dist
          path: "."

