name: Test config

on: [push]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run YAML Lint
        uses: ibiqlik/action-yamllint@v1

  home_assistant:
    runs-on: ubuntu-latest
    needs: [yamllint]
    steps:
      - uses: actions/checkout@v2

      - name: Prep stub files into configuration folder
        run: |
          cp secrets.yaml.dist secrets.yaml
          touch home-assistant_v2.db
          touch home-assistant.log
          touch OZW_Log.txt

      - name: Home Assistant version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --version

      - name: Home Assistant check config
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --config . --script check_config --info all

